# Generated by Django 4.1.7 on 2023-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
    ]
